#!/bin/bash

#####
# geo-publisher: Metadata Publication (Indexing) Project - ANU/CodeWRX
# chkconfig: 345 98 02
# description: Installer for the Geo Publisher Node application stack
#
#**************************************************************************
#   Copyright (c) 2012, The 6Th Column Project, LLC.                      *
#   Written by: The codewrx.org development team .et al                   *
#                                                                         *
#   All rights reserved. This file is part of the:                        *
#   The 6th Column Project, LLC / CodeWRX Software Stack                  *
#                                                                         *
#**************************************************************************
#             Creates an CentOS based image for Search                    *
#                                                                         *
#                                                                         *
#**************************************************************************
#                                                                         *
#   For details, see http://6thcolumn.org/                                *
#   Please also read this link                                            *
#    http://6thcolumn.org/LICENSE                                         *
#                                                                         *
#**************************************************************************

install_dir=${install_dir:-"/usr/local"}
git_branch=${BRANCH:-"master"}

install() {
    docker pull the6thcolumnproject/geo-publisher
    (($? != 0)) && echo "Sorry, Failed to install container..." && exit 1

    local scripts=(nc2es nc2geonetwork nc2json query run)
    for script in ${scripts[@]} ; do
        echo "installing ${script} "
        mkdir -p ${install_dir}/bin 
        curl --progress-bar -o ${install_dir}/bin/${script} https://raw.githubusercontent.com/the6thcolumnproject/geonetwork-docker/${git_branch}/publisher/bin/${script}
        chmod 755 ${install_dir}/bin/${script}
    done
    local script="helper.sh"
    curl --progress-bar -o ${install_dir}/bin/${script} https://raw.githubusercontent.com/the6thcolumnproject/geonetwork-docker/${git_branch}/publisher/${script}
    chmod 755 ${install_dir}/bin/${script}
    echo "install completed"
}

install
exit $?

